---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-home-volume
  namespace: jenkins
  labels:
    name: jenkins-home-volume
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: jenkins-home
    fsType: ext4