apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: jenkins:2.46.1
        ports:
        - containerPort: 80
        - containerPort: 50000
        readinessProbe:
          httpGet:
            path: /login
            port: 80
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
        securityContext:
          runAsUser: 0    # root
        env:
        - name: JENKINS_OPTS
          value: --httpPort=80
        # - name: JENKINS_OPTS
        #   valueFrom:
        #     secretKeyRef:
        #       name: jenkins
        #       key: options
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-home
        resources:
          limits:
            cpu: 500m
            memory: 1500Mi
          requests:
            cpu: 500m
            memory: 1500Mi
      - name: webhooks
        image: gcr.io/fuzzylabs-1314/webhooks:latest
        ports:
        - containerPort: 8000
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins-home-claim
