apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: jenkins
      serviceAccountName: jenkins
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app.kubernetes.io/instance"
                operator: In
                values:
                - nexus
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: jenkins
        image: jenkins/jenkins:{{ .Values.imageTag }}
        ports:
        - containerPort: 80
        - containerPort: 50000
        readinessProbe:
          httpGet:
            path: /login
            port: 80
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 2
          failureThreshold: 5
        securityContext:
          runAsUser: 0    # root
        env:
        - name: JENKINS_OPTS
          value: --httpPort=80
        volumeMounts:
        - mountPath: /var/jenkins_home
          name: jenkins-volume
        resources:
#          limits:
#            cpu: 500m
#            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
      volumes:
      - name: jenkins-volume
        gcePersistentDisk:
          pdName: jenkins-production-volume
          fsType: ext4
      tolerations:
        - effect: NoSchedule
          key: jenkins
          operator: Equal
          value: "true"
