
{{- if and .Values.server.persistentVolume.enabled (not .Values.server.persistentVolume.existingClaim)}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "jenkins.claim" . }}
  namespace: {{ template "jenkins.namespace" . }}
  annotations: 
    {{- include "jenkins.commonAnnotations" . | nindent 4 }}
  labels:
    {{- include "jenkins.commonLabels" . | nindent 4 }}
    {{- with.Values.server.persistentVolume.labels }}
    {{- toYaml . | nindent 4}}
    {{- end -}}
  {{- with.Values.server.persistentVolume.annotations }}
  annotations:
    {{- toYaml . | nindent 4}}
  {{- end -}}
{{- with .Values.server.persistentVolume }}
spec:
  {{- if .storageClass }}
  storageClassName: {{ .storageClass }}
  {{- end }}
  accessModes:
    {{- toYaml .accessMode | default "ReadWriteOnce" | nindent 4}}
  resources:
    requests:
      storage: {{ .storageSize | default "10Gi" | quote }}
  {{- if .selector }}
  selector:
  {{- toYaml .selector | nindent 4}}
  {{- end -}}
  {{- if .existingVolume }}
  volumeName: {{ .existingVolume }}
  {{- end -}}
{{- end -}}
{{- end -}}
