apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-home-ci-disk
  labels:
    app: jenkins
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  claimRef:
    name: jenkins-home-ci-disk-claim
  gcePersistentDisk:
    pdName: jenkins-home-ci-disk
    fsType: ext4

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-home-ci-disk-claim
  labels:
    app: jenkins
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "20Gi"
